import {describe,expect,it} from 'vitest';import {ImportantUnreadGmailDiscovery,SelectedNotionDiscovery,type PrivateReadGrant} from '../../src/services/radar/privateSourceDiscovery.js';
const NOW=1787932800000,owner='line:'+'a'.repeat(64),base=(scope:string,patch:Partial<PrivateReadGrant>={}):PrivateReadGrant=>({owner,bindingId:'b'.repeat(64),version:1,expiresAt:NOW+60000,scope,...patch});
describe('private Radar source boundaries',()=>{
 it('normalizes only explicitly selected Notion rows after grant recheck',async()=>{const authority={authorize:async()=>base('notion:selected:read'),read:async()=>[{pageId:'c'.repeat(64),title:'Selected page',summary:'Changed section',url:'https://www.notion.so/Selected-cccc',lastEditedAt:NOW-1000}]};
  const rows=await new SelectedNotionDiscovery(authority,()=>NOW).find(owner,10,new AbortController().signal);expect(rows[0]).toEqual(expect.objectContaining({source:'notion',title:'Selected page',metadata:['明示選択Notion']}));});
 it('keeps Gmail body out and fails closed when the binding changes',async()=>{let calls=0;const authority={authorize:async()=>base('https://www.googleapis.com/auth/gmail.metadata',{version:++calls<2?1:2}),read:async()=>[{messageId:'message_1',threadId:'thread_1',subject:'Important notice',sender:'Fixture',receivedAt:NOW-1000,url:'https://mail.google.com/mail/u/0/#inbox/message_1',body:'secret'}]};
  await expect(new ImportantUnreadGmailDiscovery(authority as any,()=>NOW).find(owner,10,new AbortController().signal)).rejects.toThrow('PRIVATE_DISCOVERY_DENIED');});
 it('returns header-only Gmail metadata with exact read scope',async()=>{const authority={authorize:async()=>base('https://www.googleapis.com/auth/gmail.metadata'),read:async()=>[{messageId:'message_1',threadId:'thread_1',subject:'Important notice',sender:'Fixture',receivedAt:NOW-1000,url:'https://mail.google.com/mail/u/0/#inbox/message_1'}]};
  const rows=await new ImportantUnreadGmailDiscovery(authority,()=>NOW).find(owner,10,new AbortController().signal);expect(rows[0]).toEqual(expect.objectContaining({source:'gmail',fact:'差出人: Fixture',metadata:['重要・未読','本文未取得']}));expect(JSON.stringify(rows)).not.toContain('body');});
});
