import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { ArtifactRenderer, type ArtifactCommandRunner } from '../../../src/services/artifacts/artifactRenderer';
import { ArtifactService } from '../../../src/services/artifacts/artifactService';
import { ArtifactStore } from '../../../src/services/artifacts/artifactStore';
import { renderTravelBriefHtml } from '../../../src/services/artifacts/travelBriefTemplate';
import type { TripBrief } from '../../../src/services/artifacts/types';

const temporaryDirectories: string[] = [];

async function makeTemporaryDirectory(): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), 'shannon-artifact-test-'));
  temporaryDirectories.push(directory);
  return directory;
}

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map(
    (directory) => rm(directory, { recursive: true, force: true }),
  ));
});

function sampleBrief(): TripBrief {
  return {
    title: '浜松 日帰りプラン',
    subtitle: '音楽と餃子を楽しむ一日',
    date: '2026年9月20日',
    introduction: '友人と無理なく巡れるプランです。',
    meetingPoint: '浜松駅 北口 10:00',
    weatherNote: '歩きやすい靴がおすすめです。',
    stops: [{
      time: '10:00',
      title: '浜松駅集合',
      place: '浜松駅',
      description: '駅で合流して当日の予定を確認します。',
      travel: '徒歩',
    }],
    highlights: ['移動を詰め込みすぎない'],
    rainPlan: ['屋内施設を中心に切り替える'],
    notes: ['営業時間は出発前に再確認'],
    sources: [{ label: '浜松市公式サイト', url: 'https://www.city.hamamatsu.shizuoka.jp/' }],
  };
}

describe('travel brief artifacts', () => {
  it('HTML内の入力値をエスケープし、スクリプトを混入させない', () => {
    const brief = sampleBrief();
    brief.title = '<script>alert(1)</script>';
    brief.sources[0].label = '公式 <b>サイト</b>';
    const html = renderTravelBriefHtml(brief);

    expect(html).not.toContain('<script>alert(1)</script>');
    expect(html).toContain('&lt;script&gt;alert(1)&lt;/script&gt;');
    expect(html).toContain('公式 &lt;b&gt;サイト&lt;/b&gt;');
    expect(html).not.toContain('<script');
  });

  it('HTML・PDF・プレビュー画像を生成し、IDから安全に解決できる', async () => {
    const rootDirectory = await makeTemporaryDirectory();
    const commands: Array<{ executable: string; args: string[] }> = [];
    const fakeRunner: ArtifactCommandRunner = async (executable, args) => {
      commands.push({ executable, args });
      await writeFile(args[args.length - 1], `generated by ${executable}`);
    };
    const store = new ArtifactStore({ rootDirectory, ttlMs: 60_000 });
    const renderer = new ArtifactRenderer(fakeRunner, { pdf: 'pdf-renderer', image: 'image-renderer' });
    const manifest = await new ArtifactService(store, renderer).createTravelBrief(sampleBrief());
    const bundle = await store.resolveBundle(manifest.id);

    expect(commands.map((command) => command.executable)).toEqual(
      expect.arrayContaining(['pdf-renderer', 'image-renderer']),
    );
    expect(bundle.files.map((file) => file.role)).toEqual(['preview', 'pdf', 'html']);
    expect(bundle.files.every((file) => file.absolutePath.startsWith(rootDirectory))).toBe(true);
    expect(bundle.manifest.kind).toBe('travel_brief');
  });

  it('任意パスや不正なIDを解決しない', async () => {
    const rootDirectory = await makeTemporaryDirectory();
    const store = new ArtifactStore({ rootDirectory });

    await expect(store.resolveBundle('../../etc/passwd')).rejects.toThrow('Invalid artifact ID');
    await expect(store.resolveBundle('not-an-artifact')).rejects.toThrow('Invalid artifact ID');
  });

  it('期限切れ成果物を削除する', async () => {
    const rootDirectory = await makeTemporaryDirectory();
    const store = new ArtifactStore({ rootDirectory, ttlMs: 10 });
    const draft = await store.createDraft();
    await writeFile(join(draft.directory, 'guide.pdf'), 'pdf');
    const manifest = await store.complete(draft, {
      kind: 'travel_brief',
      title: 'expired',
      files: [{ role: 'pdf', fileName: 'guide.pdf', mediaType: 'application/pdf' }],
    });

    expect(await store.cleanupExpired(Date.parse(manifest.expiresAt) + 1)).toBe(1);
    await expect(store.resolveBundle(draft.id)).rejects.toThrow();
  });
});
